---
name: build-push, 5-32bit-bullseye

on:
  pull_request:
  push:
    paths:
      - '5/32bit/**'
      - '.github/workflows/5.0-32bit.yml'
  schedule:
    - cron: '22 10 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    if: github.ref == 'refs/heads/testing'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 5 && cd 32bit && docker build -t redis-bullseye .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro redis-bullseye

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 5/32bit/
          file: 5/32bit/Dockerfile
          platforms: linux/amd64

          push: true
          tags: |
            ${{ github.repository }}:5.0.14-32bit, ${{ github.repository }}:5.0-32bit, ${{ github.repository }}:5-32bit, ${{ github.repository }}:5.0.14-32bit-bullseye, ${{ github.repository }}:5-32bit-bullseye
