---
name: build-push, 5.0-bullseye

on:
  pull_request:
  push:
    paths:
      - '5/**'
      - '.github/workflows/5.0-bullseye.yml'
  schedule:
    - cron: '24 *,* * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test Busybox 1.34.1-musl
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 5 && docker build -t redis-bullseye .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro redis-bullseye

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 5/
          file: 5/Dockerfile
          platforms: linux/amd64

          push: true
          tags: |
            ${{ github.repository }}:5.0.14, ${{ github.repository }}:5.0, ${{ github.repository }}:5.0.14-bullseye, ${{ github.repository }}:5.0-bullseye, ${{ github.repository }}:5-bullseye
