---
name: redis, 6.0-bullseye

on:
  pull_request:
  push:
    paths:
      - '6.0/**'
      - '.github/workflows/6.0-bullseye.yml'
  schedule:
    - cron: '47 *,* * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test Busybox 1.34.1-musl
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 6.2 && docker build -t redis-bullseye .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro redis-bullseye

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 6.0/
          file: 6.0/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:6.0-bullseye, ${{ github.repository }}:6.0.16,  ${{ github.repository }}:6.0
