---
name: build-push, 6.0-bullseye

on:
  pull_request:
  push:
    paths:
      - '6.0/**'
      - '.github/workflows/6.0-bullseye.yml'
  schedule:
    - cron: '22 10 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/testing' || github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Test building image.
        run: cd 6.0 && docker build -t redis-bullseye .

      - name: Run the built image.
        run: |
          docker run --name test-container -d -v /sys/fs/cgroup:/sys/fs/cgroup:ro redis-bullseye
          for _ in $(seq 1 30); do
            docker exec test-container redis-cli ping && exit 0
            sleep 1
          done
          docker logs test-container
          exit 1

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: test
    if: always() && (needs.test.result == 'success' || github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a
      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e

      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: 6.0/
          file: 6.0/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
                ${{ github.repository }}:6.0-bullseye,
                ${{ github.repository }}:6.0.16,
                ${{ github.repository }}:6.0
