---
#
# Ansible managed
#

name: "TODO 2 Issue"

on:
  push:

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2.4.0"
      - name: Buluma - TODO Action
        uses: buluma/todo-to-issue-action@v1.0.0
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
